version: '3'
services:

  packer-aws-runner:
    container_name: 'packer-aws-runner'
    build:
      context: ./
    image: dominikborkowski/packer-aws-runner:${TAG:-latest}
    platform: ${PLATFORM:-linux/amd64}
