name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: "Build Docker Image"
        run: |
          docker build . --tag ghcr.io/dominikborkowski/packer-aws-runner:latest
          docker push ghcr.io/dominikborkowski/packer-aws-runner:latest
